-d N:\Projekte\Soundboards\FPGA Soundboard GTB\source\HW 3.x GOSOF Tang nano 9K\impl\gwsynthesis\GOSOF80.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst N:\Projekte\Soundboards\FPGA Soundboard GTB\source\HW 3.x GOSOF Tang nano 9K\src\GOSOF80.cst
-cfg N:\Projekte\Soundboards\FPGA Soundboard GTB\source\HW 3.x GOSOF Tang nano 9K\impl\pnr\device.cfg
-sdc N:\Projekte\Soundboards\FPGA Soundboard GTB\source\HW 3.x GOSOF Tang nano 9K\src\GOSOF80.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-clock_route_order 0
-correct_hold 0
-route_maxfan 23
-global_freq 50.000
